### ISSUE TITLE
Does the Castle project have an official namespace for third-party contributions (and if so, what is is called)?

### ISSUE THREAD

**Issue by stakx** [castleproject/Home#14]
As far as I am aware, some other projects reserve the `ProjectOrCompanyName.*` namespace prefix (on NuGet) just for themselves, but they allow third-party packages under `ProjectOrCompanyName.Contrib.*`. See e.g. [SpecFlow's 2017 blog article on this](https://specflow.org/2017/nuget-packages-reserved-id-naming-conventions/).

@castleproject/pmc, does the Castle project have anything similar, i.e. a namespace (both in the sense of a C# namespace and a NuGet package prefix) dedicated to, and reserved for, third-party contributions? If so:

* What is it called?
* Is this documented somewhere?

**Comment by jonorossi** [comment]
I did consider requesting to reserve `Castle.*` when NuGet added the feature, however there unfortunately have been a lot of people publish packages under this namespace (especially some that are definitely completely unmaintained). Not sure if that allows continued use for those already using it.

I think third party packages should be under `CompanyOrUserName.*`.

**Comment by stakx** [comment]
> Not sure if that allows continued use for those already using it.

AFAIK, preexisting packages won't be affected, but people won't be able to create new packages unless they're affiliated with the Castle project and have the necessary API keys.

However, I didn't mean to imply that we *need* to do this (I agree that perhaps it's too late for that anyway, we'll never have a clean namespace with all the preexisting packages), I was mostly curious because I'm considering publishing a contrib package of my own sometime soon. :smirk:

> I think third party packages should be under `CompanyOrUserName.*`.

That's all I needed to know, so I think we can already close this. Thanks for the quick answer!

**Comment by jonorossi** [comment]
> AFAIK, preexisting packages won't be affected

Oh, maybe it is worthwhile then to stop new ones, you do get the blue verified tick on packages too IIRC. We can't clean up the past but it would at least prevent confusion like people have had with the MsDependencyInjection project which looks like a first party library.

> I'm considering publishing a contrib package of my own sometime soon

I think the concept of "contrib" (obviously short for contribution) made sense in the old days pre-Git and pre-FreeGitHosting because the contrib code used to live with the main project source code or another repo side by side. Now that people can so easily create and share their own projects, generically naming things contrib makes it hard to find the origin of a library if you search for it, so that is why I think a company or user name prefix is usually best. I bit like why it is a bad idea using `System.*` for something you'd like to see in the BCL.

Nice project btw.

**Comment by stakx** [comment]
If there *had* been a dedicated `.Contrib` namespace, I would've assumed that's the preferred way to name a package.

But I agree, using organization / username root namespaces probably makes much more sense in an ecosystem where everyone and anyone can contribute, and given today's search facilities it should be simple enough to still find extension packages.

Thanks again!
