### ISSUE TITLE
Let's brand this already ... 

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Home#5]
All docs/projects harmonised in one place. Transparent. 

Easy for desktop clr guys to interoperate with azure cloud guys when it comes to contributing. Dont forget our banking compatriates who are "eons" behind. 
 
Logo's everywhere. Complete re-brand of Castle.

Deletion of rogue templated ghpages.

**Comment by fir3pho3nixx** [comment]
Current activities. We need a drill down from the top.

**Comment by fir3pho3nixx** [comment]
Castle will live through good docs.

**Comment by fir3pho3nixx** [comment]
Going to add this again ... with more specific things.

**Comment by jonorossi** [comment]
> Going to add this again ... with more specific things.

Thanks, yer I wasn't too sure how to respond to this as it was logged.

> Deletion of rogue templated ghpages.

It was never rogue, however yes it was one of the default templates because I had to replace our old Wordpress web site years ago that was getting hacked every day. It really needs a simple and custom design, something modern. Agreed!
