### ISSUE TITLE
Documentation and Website

### ISSUE THREAD

**Issue by fir3pho3nixx** [castleproject/Home#6]
Was wondering what you want to do with the following: 

http://www.castleproject.org/

Do we want to give it a face lift or move it to a gh wiki? 

https://github.com/castleproject/Core/tree/master/docs
https://github.com/castleproject/Windsor/tree/master/docs

This has alot of stuff here, do we intended to maintain it there or do we also want to transition this over to a wiki somewhere? Should we make it all consistent? Are there markdown styling guidelines?

Would be good to clean this up and make it all look consistent.

**Comment by jonorossi** [comment]
I'd be great if the first tab on https://github.com/castleproject was "About" which was basically just a markdown rendered text, I feel GitHub doesn't make it easy to surface intro info easily. I'd be inclined to simplify the web site to a single page with links to GitHub for everything, a little like the Nancy guys have but obviously looking different.

If you are referring to the actual GitHub Wiki rather than just markdown files in the repo, then I disagree because GitHub hasn't touched their wiki in years, it only has 2 permission settings everyone can edit or only admins can edit, no good to encourage people to contribute.

I was using markdownlint (with a couple of warnings disabled, https://github.com/castleproject/Core/blob/master/docs/markdownlint.rb) to ensure consistent formatting when I moved all the docs from ScrewTurn Wiki.

I like the docs in the repo with the code which means it gets versioned together and it is easy to get someone to update the docs in a pull request if they merge together. Did you not like them in there? What did you find inconsistent with them?

If you agree I'll start work on moving the web site content into the home repo, which will make way for a new index page. There is some overlap with existing content in this repo and there is also quite a bit of out of date info on the web site.

**Comment by hconceicao** [comment]
Historically, wiki's tend to become a mess over time. Lots of unstructured/stale content,  lack of consistency,  etc.

Imo, the md + pull request will offer control and a somewhat low barrier for contributions...

**Comment by fir3pho3nixx** [comment]
Ok, got a friend of mine looking into the home page. Will post something up once he done.

**Comment by fir3pho3nixx** [comment]
What do you guys propose as the main jump links?

**Comment by fir3pho3nixx** [comment]
Home == https://github.com/castleproject/Home?

**Comment by jonorossi** [comment]
I was thinking a simple layout a bit like http://nancyfx.org/, probably with a big castle logo in the middle top, then a small box for each project with a tiny description of the main projects (DynamicProxy and Windsor) with links to their repos, then maybe a "Learn more about the Castle Project" under the projects linking to the Home repo.

**Comment by ghost** [comment]
@jonorossi 

Made a start on the new website. 

Only has the header right now. Just want to get feed back on animation and colour schemes.

http://castle.cryosharp.com/

I am thinking animated tiles for the content piece. 

Please let me know your thoughts.

**Comment by ghost** [comment]
I draw your attention to the strikthrough on the about page http://castle.cryosharp.com/#/about.

**Comment by ghost** [comment]
At this stage I more than prepared to accept design critique. Typography is hard, even for me :)

@hconceicao - Please feel free to weigh in.

**Comment by jonorossi** [comment]
> Only has the header right now. Just want to get feed back on animation and colour schemes.

I still think we should go with a single page without the need for navigation, basically a landing page like I described in https://github.com/castleproject/Home/issues/6#issuecomment-294347016.

In my mind I imagined a white background with simple structural elements for the logo and projects.
